server:
  port: 8080

spring:
  application:
    name: carevia-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/carevia}
    username: ${SPRING_DATASOURCE_USERNAME:carevia}
    password: ${SPRING_DATASOURCE_PASSWORD:carevia}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
